# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
    - 'master'

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    #Python26:
    #  python.version: '2.6'
    #  NOSEOPTS: "--verbose"
    #  SETUPOPTS: ""
    Python27:
      python.version: '2.7'
      NOSEOPTS: "--verbose --with-timer --with-xunit"
      SETUPOPTS: ""
    Python35:
      python.version: '3.5'
      NOSEOPTS: "--verbose --with-timer --with-xunit"
      SETUPOPTS: ""
    Python36:
      python.version: '3.6'
      NOSEOPTS: "--verbose --with-timer --with-xunit --xunit-file=nosetests.xml"
      SETUPOPTS: ""
    Python37:
      python.version: '3.7'
      NOSEOPTS: "--verbose --with-xunit --with-coverage --with-timer --cover-inclusive --cover-min-percentage=60 --cover-branches --cover-package=azurelinuxagent --cover-xml"
      SETUPOPTS: ""

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
  continueOnError: false

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r test-requirements.txt
  displayName: 'Install dependencies'

- script: |
   which python
   which python3
   echo $PATH
   nosetests $NOSEOPTS --attr '!requires_sudo' tests
   sudo env "PATH=$PATH" nosetests $NOSEOPTS --verbose --attr 'requires_sudo' tests
   if [ ! -z "$SETUPOPTS" ]; then /usr/bin/env python setup.py $SETUPOPTS; fi
  displayName: 'nosetest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: "**/nosetests.xml"
    testRunTitle: 'Publish test results for Python $(python.version)'
    failTaskOnFailedTests: true
    publishRunAttachments: false

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'