parameters:
  - name: scenarios
    type: object
    default:
      - agent-bvt

  - name: distros
    type: object
    default:
      - publisher: "Canonical"
        offer: "UbuntuServer"
        version: "latest"
        sku: "18.04-LTS"
        name: "ubuntu18"

trigger:
  - develop

# no PR triggers
pr: none

variables:
  - template: templates/vars.yml
  - name: SSH_PUBLIC
    value: "$(sshPublicKey)" # set in GUI variables
  - name: testsSourcesDirectory
    value: "$(Build.SourcesDirectory)/tests_e2e"


pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Execute"
    jobs:
      - template: 'templates/execute-tests.yml'
        parameters:
          scenarios:
            - ${{ parameters.scenarios }}
          distros:
            - ${{ parameters.distros }}

