#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script to update necessary flags to make agent ready for rsm updates
#
set -euo pipefail


if [[ $# -ne 1 ]]; then
    echo "Usage: agent_update-modify_agent_version <version>"
    exit 1
fi

version=$1
PYTHON=$(get-agent-python)
echo "Agent's Python: $PYTHON"
# some distros return .pyc byte file instead source file .py. So, I retrieve parent directory first.
version_file_dir=$($PYTHON -c 'import azurelinuxagent.common.version as v; import os; print(os.path.dirname(v.__file__))')
version_file_full_path="$version_file_dir/version.py"
sed -E -i "s/^AGENT_VERSION\s+=\s+'[0-9.]+'/AGENT_VERSION = '$version'/" $version_file_full_path