#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -euo pipefail

#
# The service name is walinuxagent in Ubuntu/debian and waagent elsewhere
#
# TODO: Update install-agent to use this script

usage() (
    echo "Usage: agent-service command"
    exit 1
)

if [ "$#" -lt 1 ]; then
    usage
fi
cmd=$1
shift

if [ "$#" -ne 0 ] || [ -z ${cmd+x} ] ; then
    usage
fi

if command -v systemctl &> /dev/null; then
  service-status() { systemctl --no-pager -l status $1; }
  service-stop()   { systemctl stop $1; }
  service-restart()  { systemctl restart $1; }
  service-start()  { systemctl start $1; }
else
  service-status() { service $1 status; }
  service-stop()   { service $1 stop; }
  service-restart()   { service $1 restart; }
  service-start()  { service $1 start; }
fi

if service-status walinuxagent > /dev/null 2>&1;then
    service_name="walinuxagent"
else
    service_name="waagent"
fi
echo "Service name: $service_name"

if [[ "$cmd" == "restart" ]]; then
    echo "Restarting service..."
    service-restart $service_name
fi

if [[ "$cmd" == "start" ]]; then
    echo "Starting service..."
    service-start $service_name
fi

if [[ "$cmd" == "stop" ]]; then
    echo "Stopping service..."
    service-stop $service_name
fi

if [[ "$cmd" == "status" ]]; then
    echo "Service status..."
    service-status $service_name
fi

