#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#!/usr/bin/env bash

set -euo pipefail

#
# This function enables FIPS on RHEL 7 (see https://access.redhat.com/solutions/137833)
#
# (FIPS will be enabled after reboot)
#
yum install -y dracut-fips
kernel_version=$(uname -r)
initramfs="/boot/initramfs-$kernel_version.img"
[ -f "$initramfs" ] && mv -v "$initramfs"{,.bak}
dracut -v
grubby --update-kernel=$(grubby --default-kernel) --args=fips=1
uuid=$(findmnt -no uuid /boot)
[[ -n $uuid ]] && grubby --update-kernel=$(grubby --default-kernel) --args=boot=UUID="${uuid}"
#
# Currently DCR uses Gen 1 VMs and grubby is not changing the correct file for BIOS machines.
# Check if that file was updated and, if not, update it manually. If DCR starts using Gen 2 VMs
# (which are UEFI) the changes to the BIOS file *should* not cause any issues.
#
# For more info, see "man grubby" and "3. Modify boot loader configuration." in
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-federal_standards_and_regulations#sec-Enabling-FIPS-Mode
#
if ! grep -i fips /boot/grub2/grub.cfg
then
    #
    # Add the fips and boot options to GRUB_CMDLINE_LINUX and generate a new grub.cfg
    #
    # NOTE: GRUB_CMDLINE_LINUX looks similar to
    #
    #    GRUB_CMDLINE_LINUX="crashkernel=auto console=tty1 console=ttyS0 earlyprintk=ttyS0 rootdelay=300 scsi_mod.use_blk_mq=y"
    #
    sed -i -E '/^GRUB_CMDLINE_LINUX=/s/"([^"]+)"/"\1 fips=1 boot=UUID='"$uuid"'"/' /etc/default/grub
    grub2-mkconfig -o /etc/grub2.cfg
fi

echo "FIPS will be enabled after reboot"
echo "Rebooting..."
reboot
