#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          walinuxagent
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs
# X-Start-Before:    cloud-init
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Microsoft Azure Linux Agent
### END INIT INFO

DESC="Microsoft Azure Linux Agent"
DAEMON=/usr/sbin/waagent
DAEMON_ARGS=-daemon
START_ARGS=--background
PIDFILE=/var/run/waagent.pid
