parameters:
    # see the test wiki for a description of the parameters
  - name: test_suites
    displayName: Test Suites
    type: string
    default: agent_bvt

  - name: collect_logs
    displayName: Collect logs from test VMs
    type: string
    default: failed
    values:
    - always
    - failed
    - no

  - name: skip_setup
    displayName: Skip setup of the test VMs
    type: boolean
    default: false

variables:
  - name: azureConnection
    value: 'azuremanagement'
  - name: test_suites
    value: ${{ parameters.test_suites }}
  - name: collect_logs
    value: ${{ parameters.collect_logs }}
  - name: skip_setup
    value: ${{ parameters.skip_setup }}

trigger:
  - develop

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: "ExecuteTests"

    steps:
      - task: DownloadSecureFile@1
        name: downloadSshKey
        displayName: "Download SSH key"
        inputs:
          secureFile: 'id_rsa'

      - task: AzureKeyVault@2
        displayName: "Fetch secrets from KV"
        inputs:
          azureSubscription: '$(azureConnection)'
          KeyVaultName: 'dcrV2SPs'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: '3.10'
          addToPath: true
          architecture: 'x64'

      - bash: $(Build.SourcesDirectory)/tests_e2e/pipeline/scripts/execute_tests.sh
        displayName: "Execute tests"
        continueOnError: true
        env:
          # Add all KeyVault secrets explicitly as they're not added by default to the environment vars
          AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
          AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
          AZURE_TENANT_ID: $(AZURE-TENANT-ID)
          SUBSCRIPTION_ID: $(SUBSCRIPTION-ID)

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: 'artifacts'
        displayName: 'Publish test artifacts'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'lisa/agent.junit.xml'
          searchFolder: $(Build.ArtifactStagingDirectory)
          failTaskOnFailedTests: true

