parameters:
    # See the test wiki for a description of the parameters
  - name: test_suites
    displayName: Test Suites
    type: string
    default: agent_bvt

    # NOTES:
    #         * 'image', 'location' and 'vm_size' override any values in the test suites/images definition
    #            files. Those parameters are useful for 1-off tests, like testing a VHD or checking if
    #            an image is supported in a particular location.
    #         * Azure Pipelines do not allow empty string for the parameter value, using "-" instead.
    #
  - name: image
    displayName: Image (image/image set name, URN, or VHD)
    type: string
    default: "-"

  - name: location
    displayName: Location (region)
    type: string
    default: "-"

  - name: vm_size
    displayName: VM size
    type: string
    default: "-"

  - name: collect_logs
    displayName: Collect logs from test VMs
    type: string
    default: failed
    values:
    - always
    - failed
    - no

  - name: keep_environment
    displayName: Keep the test VMs (do not delete them)
    type: string
    default: no
    values:
    - always
    - failed
    - no

variables:
  - name: azureConnection
    value: 'azuremanagement'
    # These variables exposed the above parameters as environment variables
  - name: test_suites
    value: ${{ parameters.test_suites }}
  - name: image
    value: ${{ parameters.image }}
  - name: location
    value: ${{ parameters.location }}
  - name: vm_size
    value: ${{ parameters.vm_size }}
  - name: collect_logs
    value: ${{ parameters.collect_logs }}
  - name: keep_environment
    value: ${{ parameters.keep_environment }}

trigger:
  - develop

pr: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: "ExecuteTests"

    steps:
      - task: DownloadSecureFile@1
        name: downloadSshKey
        displayName: "Download SSH key"
        inputs:
          secureFile: 'id_rsa'

      - task: AzureKeyVault@2
        displayName: "Fetch secrets from KV"
        inputs:
          azureSubscription: '$(azureConnection)'
          KeyVaultName: 'dcrV2SPs'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: '3.10'
          addToPath: true
          architecture: 'x64'

      - bash: $(Build.SourcesDirectory)/tests_e2e/pipeline/scripts/execute_tests.sh
        displayName: "Execute tests"
        continueOnError: true
        env:
          # Add all KeyVault secrets explicitly as they're not added by default to the environment vars
          AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
          AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
          AZURE_TENANT_ID: $(AZURE-TENANT-ID)
          SUBSCRIPTION_ID: $(SUBSCRIPTION-ID)

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: 'artifacts'
        displayName: 'Publish test artifacts'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'lisa/agent.junit.xml'
          searchFolder: $(Build.ArtifactStagingDirectory)
          failTaskOnFailedTests: true

