#!/usr/bin/env bash
#
# Collects the logs needed to debug agent issues into a compressed tarball.
#
set -euxo pipefail

logs_file_name="$HOME/logs.tgz"

echo "Collecting logs to $logs_file_name ..."

tar --exclude='journal/*' --exclude='omsbundle' --exclude='omsagent' --exclude='mdsd' --exclude='scx*' \
    --exclude='*.so' --exclude='*__LinuxDiagnostic__*' --exclude='*.zip' --exclude='*.deb' --exclude='*.rpm' \
    -czf "$logs_file_name" \
    /var/log \
    /var/lib/waagent/ \
    /etc/waagent.conf

# tar exits with 1 on warnings; ignore those
exit_code=$?
if [ "$exit_code" != "1" ] && [ "$exit_code" != "0" ]; then
    exit $exit_code
fi

chmod +r "$logs_file_name"

