#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Returns the PYTHONPATH on which the azurelinuxagent and associated modules are located.
#
# To do this, the script tries to find the python command used to start the agent and then
# returns the value of site.getsitepackages().
#
set -euo pipefail

# if the agent is running, get the python command from 'exe' in the /proc file system
if test -e /run/waagent.pid; then
  exe="/proc/$(cat /run/waagent.pid)/exe"
  if test -e "$exe"; then
    # exe is a symbolic link; return its target
    readlink -f "$exe"
    exit 0
  fi
fi

# try all the instances of 'python' and 'python3' in $PATH
for path in $(echo "$PATH" | tr ':' '\n'); do
  if [[ -e $path ]]; then
    for python in $(find "$path" -maxdepth 1 -name python3 -or -name python); do
      if $python -c 'import azurelinuxagent' 2> /dev/null; then
        echo "$python"
        exit 0
      fi
    done
  fi
done

# try some well-known locations
declare -a known_locations=(
  "/usr/share/oem/python/bin/python"
)
for python in "${known_locations[@]}"
do
    if $python -c 'import azurelinuxagent' 2> /dev/null; then
      echo "$python"
      exit 0
    fi
done

exit 1
