#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Returns the PYTHONPATH on which the azurelinuxagent and associated modules are located.
#
# To do this, the script tries to find the python command used to start the agent and then
# returns the value of site.getsitepackages().
#
set -euo pipefail

$(get-agent-python) -c '
import site
import os

for dir in site.getsitepackages():
  if os.path.isdir(dir + "/azurelinuxagent"):
    print(dir)
    exit(0)
exit(1)
'
