#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script runs on the container executing the tests. It creates the SSH keys (private and public) used
# to manage the test VMs taking the initial key value from the file shared by the container host, then it
# executes the daily test runbook.
#
# TODO: The runbook should be parameterized.
#
set -euxo pipefail

cd "$HOME"

# The private ssh key is shared from the container host as $HOME/id_rsa; copy it to
# HOME/.ssh, set the correct mode and generate the public key.
mkdir "$HOME/.ssh"
cp "$HOME/id_rsa" "$HOME/.ssh"
chmod 700 "$HOME/.ssh/id_rsa"
ssh-keygen -y -f "$HOME/.ssh/id_rsa" > "$HOME/.ssh/id_rsa.pub"

# Now start the runbook
lisa \
  --runbook "$HOME/WALinuxAgent/tests_e2e/scenarios/runbooks/daily.yml" \
  --log_path "$HOME/logs" \
  --working_path "$HOME/logs" \
  -v subscription_id:"$SUBSCRIPTION_ID" \
  -v identity_file:"$HOME/.ssh/id_rsa.pub"
