#!/usr/bin/env bash

# Microsoft Azure Linux Agent
#
# Copyright 2018 Microsoft Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script runs on the container executing the tests. It creates the SSH keys (private and public) used
# to manage the test VMs taking the initial key value from the file shared by the container host, then it
# executes the daily test runbook.
#
set -euxo pipefail

usage() (
    echo "Usage: run-scenarios  [-t|--test-suites <test suites>] [-l|--collect-logs <always|failed|no>] [-k|--skip-setup <True|False>]"
    exit 1
)

test_suite_parameters=""

while [[ $# -gt 0 ]]
do
    case $1 in
        -t|--test-suites)
            shift
            if [ "$#" -lt 1 ]; then
                usage
            fi
            test_suite_parameters="$test_suite_parameters -v test_suites:$1"
            ;;
        -l|--collect-logs)
            shift
            if [ "$#" -lt 1 ]; then
                usage
            fi
            test_suite_parameters="$test_suite_parameters -v collect_logs:$1"
            ;;
        -k|--skip-setup)
            shift
            if [ "$#" -lt 1 ]; then
                usage
            fi
            test_suite_parameters="$test_suite_parameters -v skip_setup:$1"
            ;;
        *)
          usage
    esac
    shift
done

# The private ssh key is shared from the container host as $HOME/id_rsa; copy it to
# $HOME/.ssh, set the correct mode and generate the public key.
cd "$HOME"
mkdir .ssh
cp id_rsa .ssh
chmod 700 .ssh/id_rsa
ssh-keygen -y -f .ssh/id_rsa > .ssh/id_rsa.pub

#
# Now start the runbook
#
lisa_logs="$HOME/logs/lisa"

lisa \
  --runbook "$HOME/WALinuxAgent/tests_e2e/orchestrator/runbook.yml" \
  --log_path "$lisa_logs" \
  --working_path "$lisa_logs" \
  -v subscription_id:"$SUBSCRIPTION_ID" \
  -v identity_file:"$HOME/.ssh/id_rsa" \
  $test_suite_parameters
