parameters:
  - name: scenarios
    type: object

  - name: distros
    type: object

  - name: rgPrefix
    type: string

jobs:
  - job: "Cleanup"
    dependsOn: "Wait"
    condition: always()

    strategy:
      matrix:
        ${{ each scenario in parameters.scenarios }}:
          ${{ format('{0}', scenario) }}:
            scenarioName: ${{ scenario }}
            rgName: ${{ format('{0}-{1}', parameters.rgPrefix, scenario) }}
      maxParallel: 50

    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: "Delete test RG"
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(azureConnection)'
          subscriptionId: '$(subId)'
          action: 'DeleteRG'
          resourceGroupName: '$(rgName)'