#!/bin/sh
set -e

if [ -f /usr/sbin/waagent.save ]; then
    dpkg-divert --package walinuxagent-data-saver --rename --remove /usr/sbin/waagent
fi

case "$1" in
    configure)
        waagent --setup --force
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        if [ -f /etc/init.d/waagent ]; then
            rm /etc/init.d/waagent
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

